import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import path from "path"
import fs from "fs"

export default defineConfig(({ mode }) => {
  // Read the Canister IDs directly from the .env file generated by dfx in the root
  const envPath = path.resolve(__dirname, '../../.env');
  let envVars = {};
  if (fs.existsSync(envPath)) {
    const envFile = fs.readFileSync(envPath, 'utf-8');
    envFile.split('\n').forEach(line => {
      const [key, value] = line.split('=');
      if (key && value) {
        // Expose Canister IDs to Vite with the VITE_ prefix
        envVars[`VITE_${key}`] = JSON.stringify(value.replace(/"/g, ''));
      }
    });
  }

  return {
    plugins: [react()],
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
      },
    },
    define: envVars // Inject the variables into the app
  }
})
